---
date: last-modified
bibliography: References.bib
csl: harvard-cite-them-right.csl
title: CASA0007 Assessment Submission
execute:
  echo: false
  freeze: true
format:
  html:
    code-copy: true
    code-link: true
    toc: true
    toc-title: On this page
    toc-depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    mainfont: "Source Serif 4"
    sansfont: "Source Sans 3"
    monofont: "Source Code Pro"
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: false
    colorlinks: true
    highlight-style: github
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.15.2
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

## Declaration of Authorship {.unnumbered .unlisted}

I, Tee Chin Min Benjamin, pledge my honour that the work presented in this assessment is my own. Where information has been derived from other sources, I confirm that this has been indicated in the work. Where a Large Language Model such as ChatGPT has been used I confirm that we have made its contribution to the final submission clear.

Date: 12 January 2026 (Tues)

Student Number: 25049107  

{{< pagebreak >}}

# Project Setup 




# Article 




# Technical Appendix

```{python}
#| echo: True 
# This code will be shown, 
# but the next block will not
import os
import pandas as pd
```

```{python}
# This code is not shown because echo was
# set to False in the header. You should
# think carefully about whether you want
# or need to show any code to the reader
# in the PDf.
host = 'https://orca.casa.ucl.ac.uk'
path = '~jreades/data'
file = '20250615-London-listings.parquet'

if os.path.exists(file):
  df = pd.read_parquet(file)
else: 
  df = pd.read_parquet(f'{host}/{path}/{file}')
  df.to_parquet(file)
```

An inline citation example: As discussed on @insideairbnb, there are many...

A parenthetical citation example: There are many ways to research Airbnb [see, for example, @insideairbnb]... 

```{python}
#| output: asis
# This is one way to write dynamic text. 'As is' means
# it will interpret the result as regular Quarto markdown 
# so the below `print` statement becomes plain text with
# the size of the dataframe interpolated into the string.
# When Quarto is done running the Python code what's left
# is plain-text and that is then treated as a paragraph
# like it would be if you'd written it in Quarto.
print(f"One of way to embed output in the text looks like this: after cleaning, we were left with {df.shape[0]:,} rows of data.")
```

```{python}
# The other way is to ensure that your variables are *simple* 
# data types that Quarto can understand. So notice below that
# we just have a single, inline `{python} with the value of
# the row directly inserted into the sentence. his should also work, but is sometimes less predictably
# reliable.
row_count = f"{df.shape[0]:,}"
```
The other way is to interpolate it directly into the sentence like this (`{python} row_count `); however, I've found it less reliable and it really requires you to be careful about data types. So `{python} print(f"{df.shape[0]:,}") ` probably won't work and you'll just see some Python code instead.

And here's a nice little chart straight into the document!

```{python}
ax = df.host_listings_count.plot.hist(bins=50);
ax.set_xlim([0,500]);
```

{{< pagebreak >}}


## References